name: Build

on:
  pull_request:
    branches:
      - main
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        tf-version: [1.4.4, 1.5.7, 1.6.6]
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
          TERRAFORM_VERSION=${{ matrix.tf-version }}
          curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          rm *
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/runner/go/pkg/mod
          key: go-mod
      - name: Build provider and install
        run: |
          make install
      - name: Validate against examples
        run: |
          find ~/.terraform.d/plugins/
          make examples
